export enum Function {
  TIME_SERIES_INTRADAY = 'TIME_SERIES_INTRADAY',
  SYMBOL_SEARCH = 'SYMBOL_SEARCH',
  TIME_SERIES_DAILY_ADJUSTED = 'TIME_SERIES_DAILY_ADJUSTED',
  TIME_SERIES_WEEKLY_ADJUSTED = 'TIME_SERIES_WEEKLY_ADJUSTED',
  TIME_SERIES_MONTHLY_ADJUSTED = 'TIME_SERIES_MONTHLY_ADJUSTED',
  OVERVIEW = 'OVERVIEW',
  CRYPTO_INTRADAY = 'CRYPTO_INTRADAY',
  DIGITAL_CURRENCY_MONTHLY = 'DIGITAL_CURRENCY_MONTHLY',
}
